### ISSUE TITLE
[FEATURE] Claims

### ISSUE THREAD

**Issue by Strike5223** [Gunpowder-MC/Gunpowder#100]
I was wondering if you'd consider doing something like a factions and also a worldprotect type of mod. I know there are already some mods out there like this however they aren't compatible for one with each other and aren't offering some nice features that would be sick to see.

**Comment by martmists-gh** [comment]
In that case, let me ask some questions.
How should the following be handled:
- TNT/Explosions (someone could even lure creepers to your base)
- Redstone/Pistons (could be used for griefing)
- Fire (either through firespread or magic mods or whatever)
- Lightning created by Channeling or other mods
- Modded blockentities (like CC:R turtles)
- Frost Walker (may e.g. screw up farms or sorting systems or the like)
- Minecarts (can be used to pick up and move around entities)

Note that for pretty much all of these cases, it's impossible to figure out what player caused it, and as such I can't check if the user is allowed to do so or not, and it'll have to be a rule applying for everyone.

**Comment by Samisafool** [comment]
Was this actually completed? I don't see commits

**Comment by Martmists-GH** [comment]
I've closed all feature requests as I'm migrating issues to youtrack, which will take some time. I'll also re-evaluate whether some of these are required to be implemented by Gunpowder, as e.g. GOML already implements a way to protect land and I'd simply be reinventing the wheel.
