### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by srnyx** [Gunpowder-MC/Gunpowder#101]
**Information**
- Minecraft Version: 1.16.5
- Fabric API Version: 0.32.9
- OS: IDK
- Other installed mods: https://www.curseforge.com/minecraft/modpacks/simpearth (not all of them, there are also server-side mods too)

**Describe the issue**
Server crashes upon start-up

**Crash/Error logs**
https://paste.srnyx.xyz/inotifijaz.sql

**Expected behavior**
Server should start

**Additional Context**
I just recently updated Gunpowder Base to the latest version.

**Comment by williambl** [comment]
I think this is the cause of the issue:

![image](https://user-images.githubusercontent.com/5115825/115148258-4b878d00-a04e-11eb-8cad-213836ac0a33.png)

Kotlin [doesn't compile default methods as java does unless you tell it to](https://dev.to/williambl/mixins-kotlin-and-default-methods-why-they-don-t-work-together-417d), it makes an inner class to the interface called `DefaultImpls`, then adds synthetic implementation methods that call static methods in that inner class to classes that do not override the 'default' methods.

However, most gunpowder modules have not been recompiled against this new version of gunpowder-base, and so do not have these synthetic implementing methods and crash with an `AbstractMethodError`.

**Comment by martmists-gh** [comment]
damn you kotlin

I'll fix this later tonight
