### ISSUE TITLE
Quilt "breakage"

### ISSUE THREAD

**Issue by gdude2002** [Gunpowder-MC/Gunpowder#102]
For whatever reason GitHub won't let me respond to [this comment thread](https://github.com/Gunpowder-MC/Gunpowder/commit/185eb1585497d0e39a61486e525efb6d28fdf211#r49653158), (returns a 422 Unprocessable Entity), so I figured I'd just make an issue.

> It's mainly to avoid errors from quilt users ahead of time, in cases where it'd run fine on fabric. I only target fabric while developing, so issues from quilt users will just be closed anyway. This way I can prevent that altogether.

In short, this comment doesn't make sense, and this change was bundled up within a larger commit and not mentioned in the commit message - which is kinda sus, my dude. 

We're not projecting any breakages of this type (do we look like Optifine?), compatibility should be simple enough to maintain, and as a _very_ community-driven project there will be no issues getting things fixed if they _do_ break. Reporting breakages and working with us on fixes will be far more productive than... Whatever this statement is supposed to be.

The most context I can gather is that Mart had an argument with someone who has literally nothing to do with Quilt. I 100% respect that it's a modder's decision when thinking about what technologies, but I would like to see more context for this than a deliberately hidden change in an unrelated commit with reasoning that doesn't seem entirely clear.

If it's something you don't want to share publicly, that's fine - Mart, feel free to drop me a DM on Discord, and we'll hash things out. I'm probably still in your DM list, haha

**Comment by SpaceClouds42** [comment]
The reason is after responding to my comment, @martmists-gh locked it to collaborators only.
![image](https://user-images.githubusercontent.com/71787666/115320073-1fa00080-a14f-11eb-94a6-362c2d6a3f00.png)

**Comment by SpaceClouds42** [comment]
> I only target fabric while developing, so issues from quilt users will just be closed anyway.

I'd also like to point out that a comment at the top of your readme or mod listing saying that you only develop for fabric and won't fix incompatibilities on quilt would get the job done. That way, in the *likely* case that it is compatible, quilt users could still use the your mod, and if it's not, oh well, nobody is asking you to actively support it. You'd probably even get a pr from someone fixing quilt incompatibility if it were possible to fix it.

**Comment by TehcJS** [comment]
when the impostor is sus :flushed: 
mart, you do realize that the only "incompatibility" is mod devs that don't like the idea of a fork of fabric
quilt will be compatible with fabric. there will be little compatibility issues. this isn't optifine smh

**Comment by SpaceClouds42** [comment]
:concern:

**Comment by gdude2002** [comment]
No worries Mart, no obligation. Catch you on the flipside, maybe!
