### ISSUE TITLE
Server crash 2

### ISSUE THREAD

**Issue by srnyx** [Gunpowder-MC/Gunpowder#103]
**Information**
- Minecraft Version: 1.16.5
- Fabric API Version: 0.33.0

**Describe the issue**
Server crashes on start

**Crash/Error logs**
https://paste.srnyx.xyz/ulisasiziw.sql

**Comment by martmists-gh** [comment]
Can you show your config for gunpowder?

**Comment by srnyx** [comment]
> Can you show your config for gunpowder?

https://paste.srnyx.xyz/zacinonofu.yaml

**Comment by martmists-gh** [comment]
Contact me on discord, I'll have some things I'll need you to test (I can't upload jars sadly)

**Comment by Monster-Zer0** [comment]
bump... I am also having this issue. https://paste.srnyx.xyz/ulisasiziw.sql
