### ISSUE TITLE
Shift-click on ChestGUI button which closes the GUI gives player the button itemstack

### ISSUE THREAD

**Issue by williambl** [Gunpowder-MC/Gunpowder#104]
**Information**
- Minecraft Version: 1.16.5
- Fabric API Version: 0.32.0
- OS: Manjaro
- Other installed mods: 

**Describe the issue**
A ChestGUI button with code like:
```kt
button(0, 0, Items.BEDROCK.defaultStack) { actionType, container ->
	/* do stuff */
	player.closeHandledScreen()
}   
```
will allow the player to take the button itemstack by shift-clicking. This is because, in `ChestGuiContainer#onSlotClick`, there is this code:
```kt
if (buttons.containsKey(slotId)) {
    val button = buttons[slotId]!!
    button.callback.invoke(actionType, this)
}

// Avoid desyncs
inventory.markDirty()
(playerEntity as ServerPlayerEntity).server.playerManager.sendToAll(InventoryS2CPacket(syncId, playerEntity.currentScreenHandler.stacks))
sendContentUpdates()

return ItemStack.EMPTY
```
The screenhandler is closed before the 'avoid desyncs' code is run. This can be avoided by swapping the 'avoid desyncs' and the button handling code.

**To Reproduce**
Create a ChestGUI with code like:
```kt
button(0, 0, Items.BEDROCK.defaultStack) { actionType, container ->
	/* do stuff */
	player.closeHandledScreen()
}   
```
, then shift-click on it.

**Expected behavior**
The player should not be given the button itemstack.

**Comment by martmists-gh** [comment]
> This can be avoided by swapping the 'avoid desyncs' and the button handling code.
If this is swapped, then the action is triggered AFTER the contents are sent, and as such it will desync. I recommend not having a button to close the screen for now.
