### ISSUE TITLE
Travelling through End Portal gives "Internal Server Error"

### ISSUE THREAD

**Issue by ablos** [Gunpowder-MC/Gunpowder#106]
**Information**
- Minecraft Version: 1.16.5
- Gunpowder Base version: 0.5.2+1.16.5
- Fabric API Version: fabric-api-0.33.1+1.16
- OS: Windows (However it also happens on my server host which I think uses Linux, but not sure)
- Other installed mods: Fabric API, Fabric Language Kotlin (Also Lithium, Phosphor and Gunpowder Teleport, however without those loaded the bug still appears)

**Describe the issue**
With Gunpowder Base loaded, entering the end portal gives an "Internal Server Error" which forces the player to disconnect. Upon rejoining the error immediatly reappears. I had to load the server without Gunpowder Base to get out of the portal. Items also don't travel through the portal.
For players this only happens when travelling from the overworld to the end. Going back from the end to the overworld the player experiences no problems, however items still don't travel through that portal (end to overworld).
The portals to go to the end city part of the end do work normally (both players and items travel through them without problems)

**Crash/Error logs**
https://pastebin.com/wwJwfTmP
(I started the server with Gunpowder Base loaded, travelled through the portal, got disconnected by the "Internal Server Error" and closed the server)

**To Reproduce**
1. Go to an End Portal
2. Go through / throw an item through
3. The "Internal Server Error" message should appear (Only End > Overworld portal) / the item in the end should not appear (same for End > Overworld portal)
4. To get out of "Internal Server Error" loop, restart server without Gunpowder Base loaded

**Expected behavior**
The player should go through the portal without any problems. Items should also travel through the portal and appear in the other dimension.

**Additional context**
I updated all mods and the Fabric server. The problem already occured in Gunpowder Base version 0.4.5+1.16.5 (after trying to update Gunpowder Base the problem still occured, that is why I am reporting this). I tested all the behaviour in a vanilla server and in a Fabric server without mods and in a Fabric server with all mods (but without Gunpowder) and in all these cases the player and items were able to travel through the portals without any problems.

**Comment by martmists-gh** [comment]
> 	at net.minecraft.class_1937.method_8518(class_1937.java:191) ~[intermediary-server.jar:?]
 I'm pretty sure I don't inject anything here, I'll look into it.

**Comment by Copaface** [comment]
I have the same issue!

**Comment by Castlegrave** [comment]
+1 for this issue :(

**Comment by magneticflux-** [comment]
My analysis:

Somehow `Entity#lastNetherPortalPosition` is null unexpectedly. It's null for new entities until `setInNetherPortal` or `copyFrom` is called.

`setInNetherPortal` is only called by `NetherPortalBlock`'s entity collision handler, which might be the problem. The `comingFromNether` and `goingToNether` mixins could force a teleport to/from the Nether when not in a `NetherPortalBlock`, which violates the assumption that `lastNetherPortalPosition` is non-null.
