### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by srnyx** [Gunpowder-MC/Gunpowder#107]
**Information**
- Minecraft Version: 1.16.5
- Fabric API Version: 0.34.0
- OS: IDK
- Other installed mods: https://imgur.com/a/EmuyjcW

**Describe the issue**
The server crashes on startup

**Crash/Error logs**
https://paste.srnyx.xyz/akejuputos.pl

**Comment by martmists-gh** [comment]
downgrade fabric API

**Comment by srnyx** [comment]
> downgrade fabric API

Worked, thanks
