### ISSUE TITLE
Crash when launching with 1.17-rc2

### ISSUE THREAD

**Issue by bentterp** [Gunpowder-MC/Gunpowder#110]
**Information**
- Minecraft Version:1.17-rc2
- Fabric API Version: 0.34.9-1.17
- OS: Windows 10 64 bit
- Other installed mods: [Leave empty if nothing else is installed]

**Describe the issue**
Crashes upon launch

**Crash/Error logs**
https://paste.ee/p/6KtQ6

If the game crashes or console errors are present, please attach the log here using a text paste service (such as gist or hastebin):

**To Reproduce**

**Expected behavior**

**Additional context**
Java 16

**Comment by martmists-gh** [comment]
Your gunpowder.yaml seems old and incomplete, make sure to delete it to let it regenerate.

**Comment by bentterp** [comment]
sorry, should have thought of that. fixes the issue as you expected
