### ISSUE TITLE
Crashes without fabric-language-kotlin

### ISSUE THREAD

**Issue by Samisaprogrammer** [Gunpowder-MC/Gunpowder#111]
**Information**
- Minecraft Version: 1.16.5
- Fabric API Version: 0.34.6
- OS: Windows
- Other installed mods:

**Describe the issue**
Crashes without fabric-language-kotlin

**To Reproduce**
1. Run mod alongside fabric api
2. Minecraft crashes

**Expected behavior**
Fabric should give an error about fabric-language-kotlin not being installed

**Additional context**

**Comment by Samisaprogrammer** [comment]
Fixed when fabric-language-kotlin is installed

**Comment by martmists-gh** [comment]
Yes fabric language kotlin is listed as dependency on curseforge

**Comment by Samisaprogrammer** [comment]
Well it does not give me an error saying fabric language kotlin is required which is what i expect, it just gives me a crash with a single reference to kotlin.

**Comment by martmists-gh** [comment]
Sounds like an issue with fabric loader, fabric-language-kotlin is definitely specified in the mod json.
