### ISSUE TITLE
Proper permissions support

### ISSUE THREAD

**Issue by ggtylerr** [Gunpowder-MC/Gunpowder#112]
_**Note: This request is more so for the current official modules. This is only on the main repo so there isn't a request made for each individual module.**_

**Describe what you'd like**
Currently, none of the modules support the LuckPerms API, or any permission API AFAIK. (I've read that Player Roles somewhat work, but it's not officially supported.) This can be an issue as many admins use LuckPerms or a similar permissions plugin, and the ambiguity of certain commands only being allowed to be used by 'admins' (op) can be difficult to deal with. 

**Additional context**
Let's say you have two different groups: Moderators and Admins. Mods are only supposed to moderate, so they have limited permissions. (i.e. they can ban someone, but they can't use WorldEdit or other unnecessary commands.) Admins have full permissions, able to run any command.

At the mods' current state, it is not possible to separate between these two for Gunpowder commands. Let's say you want mods to have the ability to make warps, but don't want to give them op. You simply can't do that right now. With support for LuckPerms, you can, you'd just add that permission, like `gunpowder.teleport.setwarp`

**Comment by martmists-gh** [comment]
Permission API has been held off until the API support numeric permissions, which luckperms' api does not. There is a new proposal in the works by @Patbox but it is far from complete and final, and mostly just a draft as of right now. 

Once numeric permissions are supported by an API and there exists an implementation for it (such as luckperms), I'll happily add support for it.

**Comment by BradBot1** [comment]
> Once numeric permissions are supported by an API and there exists an implementation for it (such as luckperms), I'll happily add support for it.

Do you mind explaining what you mean by 'numeric permissions'? I am guessing things like example.permission.1 but i wish to check

**Comment by martmists-gh** [comment]
Yup, exactly. I want to add all permissions in one go, which means permission nodes like e.g. `homes.limit.10` needs to be supported.
