### ISSUE TITLE
/home crashing server. Unexpected value of type BlockPos: 63 of kotlin.Int

### ISSUE THREAD

**Issue by dandin87** [Gunpowder-MC/Gunpowder#113]
**Information**
- Minecraft Version: 1.17
- Fabric API Version: fabric-api-0.36.0+1.17.jar, fabric-language-kotlin-1.6.1+kotlin.1.5.10.jar
- OS: Linux (amd64) version 4.15.0-126-generic
- Other installed mods: All Of Fabric 4

**Describe the issue**
Server crash on player using /home command

**Crash/Error logs**
If the game crashes or console errors are present, please attach the log here using a text paste service (such as gist or hastebin):
https://paste.alloffabric.com/oqocenoduc.yaml

**To Reproduce**
This started happening out of nowhere, not sure its reproducible except on our server. Going to include the database as well as its only 128kb

**Expected behavior**
Not Crash

**Additional context**
[gunpowder.zip](https://github.com/Gunpowder-MC/Gunpowder/files/6722172/gunpowder.zip)
gunpowder-base-1.0.3.2+1.17.jar
gunpowder-teleport-1.0.8+gunpowder.1.0.1.mc.1.17.jar

**Comment by martmists-gh** [comment]
Did you recently update from an older version of Gunpowder Teleport?
