### ISSUE TITLE
Halts server upon use 

### ISSUE THREAD

**Issue by RagingFlamesOfficial** [Gunpowder-MC/Gunpowder#114]
**Information**
- Minecraft Version: [e.g. 20w13a] 1.17
- Fabric API Version: [e.g. 0.5.1+build.294-1.15] api-ver 36.0+1.17 fabric-loader-0.11.6-1.17 
- OS: [e.g. Windows, Mac OS, Ubuntu] Windows
- Other installed mods: [Leave empty if nothing else is installed]

**Describe the issue**
A clear and concise description of what the bug is. After adding gunpowder-base. I would start the server let it do its thing. Then i'd get towards the end a null/void pointer for database. Config is setup to connect to our private MYSQL database. I don't get this issue without the mod on the server.

**Crash/Error logs**
If the game crashes or console errors are present, please attach the log here using a text paste service (such as gist or hastebin):
https://paste.alloffabric.com/bivemoyecu.properties
**To Reproduce**

add to 1.17 fabric-0.11.3-6 server
start the server
get the error.
redid the config in case.
Still got error after restarting!

**Expected behavior**

Wasn't really expecting it to this in the first place.  Was expecting it to work without any issues

**Additional context**
gunpowder-base-1.0.5+1.17

**Comment by martmists-gh** [comment]
Seems like Ledger is using an old version of Exposed.
