### ISSUE TITLE
Says permission API missing while it is there.

### ISSUE THREAD

**Issue by AchalS-iglu** [Gunpowder-MC/Gunpowder#117]
`[12:08:35] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Errors were found!
 - Missing mods: fabric-permissions-api-v0
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:342) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
`

**Comment by AchalS-iglushrek** [comment]
The permissions API is def intalled, I am using the currency and base module. I have player roles that does use permissions api

**Comment by martmists-gh** [comment]
I'm not sure if Player Roles is compatible with the permission API we use. Can you give your full mod list?

**Comment by AchalS-iglushrek** [comment]
Sorry for the late reply but here, I will try removing player roles and ig then I can use your permissions mod

`environment-type: SERVER
development-environment: false
launch-arguments: [nogui]
operating-system: {arch: amd64, name: Linux, version: 5.4.0-1051-azure}
java: {vendor: AdoptOpenJDK, vendor-url: 'https://adoptopenjdk.net/', version: 16.0.1}
mods:
- {mod-id: adventure-platform-fabric, name: adventure-platform-fabric, version: 4.1.0-SNAPSHOT,
    authors: 'kashike, zml, Luck, Electroid'}
- {mod-id: aegis, name: Aegis, version: 3.0.0, authors: P03W/TheoreticallyUseful}
- {mod-id: autoconfig1u, name: Auto Config v1 Updated, version: 3.3.1, authors: 'sargunv,
        shedaniel'}
- {mod-id: axesareweapons, name: Axes Are Weapons, version: 1.3-1.17, authors: Fourmisain}
- {mod-id: blame, name: Blame, version: 1.17-4.0.0-fabric, authors: TelepathicGrunt}
- {mod-id: bluemap, name: BlueMap, version: 1.5.3, authors: 'Blue (TBlueF, Lukas Rieger)'}
- {mod-id: c2me, name: Concurrent Chunk Management Engine, version: 0.2.0+alpha.1.0,
    authors: 'ishlandbukkit, ishland'}
- {mod-id: carpet, name: Carpet Mod, version: 1.4.40, authors: 'gnembon, ...'}
- {mod-id: chunkpregen, name: Fabric Chunk Pregenerator, version: 0.3.3, authors: SuperCoder79}
- {mod-id: cloth-basic-math, name: Cloth Basic Math, version: 0.5.1, authors: shedaniel}
- {mod-id: cloth-config2, name: Cloth Config v4, version: 5.0.34, authors: shedaniel}
- {mod-id: cloud-v1, name: Cloud, version: 1.5.0-SNAPSHOT, authors: 'Citymonstret,
        zml, jmp'}
- {mod-id: compostable-rottenflesh, name: Compostable Rotten Flesh, version: 1.0.0,
    authors: LumpyMonkey}
- {mod-id: confabricate, name: confabricate, version: 2.1.0-SNAPSHOT+4.1.1, authors: zml}
- {mod-id: cotton-config, name: Cotton Config, version: 1.0.0-rc.7}
- {mod-id: cotton-logging, name: Cotton Logging, version: 1.0.0-rc.4}
- {mod-id: crossstitch, name: CrossStitch, version: 0.1.4, authors: 'Andrew Steinborn,
        Velocity Contributors'}
- {mod-id: defibrillator, name: Defibrillator, version: 1.5.0, authors: TheoreticallyUseful
        / P03W}
- {mod-id: discerning_furnace, name: Discerning Furnace, version: 1.0.3+MC1.17-1.17.1,
    authors: supersaiyansubtlety}
- {mod-id: disfabric, name: DisFabric, version: 1.3.3, authors: 'BRForgers Team, armelin1,
        D4rkness_King, jonatsp'}
- {mod-id: easy_painter, name: Easy Painter, version: 1.0.2, authors: aws404}
- {mod-id: endermenarefriends, name: Endermen Are Friends, version: 1.1-mc1.17-fabric,
    authors: alkyaLy}
- {mod-id: essential_commands, name: Essential Commands, version: 0.13.2-beta-mc1.17,
    authors: John Paul R. (JP79194)}
-   mod-id: fabric
    name: Fabric API
    version: 0.36.0+1.17
    authors: FabricMC
    children:
    - {mod-id: fabric-api-base, name: Fabric API Base, version: 0.3.0+a02b44633d,
        authors: FabricMC}
    - {mod-id: fabric-api-lookup-api-v1, name: Fabric API Lookup API (v1), version: 1.2.0+2b5c62d03d,
        authors: FabricMC}
    - {mod-id: fabric-biome-api-v1, name: Fabric Biome API (v1), version: 3.1.11+c345aea83d,
        authors: FabricMC}
    - {mod-id: fabric-command-api-v1, name: Fabric Command API (v1), version: 1.1.1+a02b44633d,
        authors: FabricMC}
    - {mod-id: fabric-commands-v0, name: Fabric Commands (v0), version: 0.2.2+92519afa3d,
        authors: FabricMC}
    - {mod-id: fabric-containers-v0, name: Fabric Containers (v0), version: 0.1.12+a02b44633d,
        authors: FabricMC}
    - {mod-id: fabric-content-registries-v0, name: Fabric Content Registries (v0),
        version: 0.2.2+a02b44633d, authors: FabricMC}
    - {mod-id: fabric-crash-report-info-v1, name: Fabric Crash Report Info (v1), version: 0.1.5+be9da3103d,
        authors: FabricMC}
    - {mod-id: fabric-dimensions-v1, name: Fabric Dimensions API (v1), version: 2.0.10+a02b44633d,
        authors: FabricMC}
    - {mod-id: fabric-entity-events-v1, name: Fabric Entity Events (v1), version: 1.1.0+a02b44633d,
        authors: FabricMC}
    - {mod-id: fabric-events-interaction-v0, name: Fabric Events Interaction (v0),
        version: 0.4.9+a722d8c03d, authors: FabricMC}
    - {mod-id: fabric-events-lifecycle-v0, name: Fabric Events Lifecycle (v0), version: 0.2.1+92519afa3d,
        authors: FabricMC}
    - {mod-id: fabric-game-rule-api-v1, name: Fabric Game Rule API (v1), version: 1.0.6+a02b44633d,
        authors: FabricMC}
    - {mod-id: fabric-item-api-v1, name: Fabric Item API (v1), version: 1.2.4+a02b44633d,
        authors: FabricMC}
    - {mod-id: fabric-item-groups-v0, name: Fabric Item Groups (v0), version: 0.2.10+b7ab61213d,
        authors: FabricMC}
    - {mod-id: fabric-lifecycle-events-v1, name: Fabric Lifecycle Events (v1), version: 1.4.4+a02b44633d,
        authors: FabricMC}
    - {mod-id: fabric-loot-tables-v1, name: Fabric Loot Tables (v1), version: 1.0.4+a02b44633d,
        authors: FabricMC}
    - {mod-id: fabric-mining-levels-v0, name: Fabric Mining Levels (v0), version: 0.1.3+92519afa3d,
        authors: FabricMC}
    - {mod-id: fabric-networking-api-v1, name: Fabric Networking API (v1), version: 1.0.11+b7ab61213d,
        authors: FabricMC}
    - {mod-id: fabric-networking-blockentity-v0, name: Fabric Networking Block Entity
            (v0), version: 0.2.11+a02b44633d, authors: FabricMC}
    - {mod-id: fabric-networking-v0, name: Fabric Networking (v0), version: 0.3.2+92519afa3d,
        authors: FabricMC}
    - {mod-id: fabric-object-builder-api-v1, name: Fabric Object Builder API (v1),
        version: 1.10.9+b7ab61213d, authors: FabricMC}
    - {mod-id: fabric-object-builders-v0, name: Fabric Object Builders (v0), version: 0.7.3+a02b44633d,
        authors: FabricMC}
    - {mod-id: fabric-particles-v1, name: Fabric Particles (v1), version: 0.2.4+a02b44633d,
        authors: FabricMC}
    - {mod-id: fabric-registry-sync-v0, name: Fabric Registry Sync (v0), version: 0.7.10+e2961fee3d,
        authors: FabricMC}
    - {mod-id: fabric-rendering-data-attachment-v1, name: Fabric Rendering Data Attachment
            (v1), version: 0.1.5+a02b44633d, authors: FabricMC}
    - {mod-id: fabric-resource-loader-v0, name: Fabric Resource Loader (v0), version: 0.4.7+b7ab6121a0,
        authors: FabricMC}
    - {mod-id: fabric-screen-handler-api-v1, name: Fabric Screen Handler API (v1),
        version: 1.1.8+a02b44633d, authors: FabricMC}
    - {mod-id: fabric-structure-api-v1, name: Fabric Structure API (v1), version: 1.1.11+e36969833d,
        authors: FabricMC}
    - {mod-id: fabric-tag-extensions-v0, name: Fabric Tag Extensions (v0), version: 1.1.4+a02b44633d,
        authors: FabricMC}
    - {mod-id: fabric-tool-attribute-api-v1, name: Fabric Tool Attribute API (v1),
        version: 1.2.12+b7ab61213d, authors: FabricMC}
- {mod-id: fabric-language-kotlin, name: Fabric Language Kotlin, version: 1.6.2+kotlin.1.5.20,
    authors: Nikky}
- {mod-id: fabric-permissions-api-v0, name: fabric-permissions-api, version: 0.1-SNAPSHOT,
    authors: Luck}
- {mod-id: fabriccrossdimtpfix, name: FabricCrossDimTPFix, version: 0.2.0}
- {mod-id: fabricloader, name: Fabric Loader, version: 0.11.6, authors: FabricMC}
- {mod-id: fabricproxy-lite, name: FabricProxy Lite, version: 1.1.4, authors: james58899}
- {mod-id: fabrictailor, name: Fabric Tailor, version: 1.6.1, authors: samo_lego}
- {mod-id: ferritecore, name: FerriteCore, version: 3.0.1, authors: malte0811}
- {mod-id: flan, name: Flan, version: 1.17-1.5.4, authors: Flemmli97}
- {mod-id: gimme_bundles, name: Gimme bundles!, version: 1.0.1, authors: Fulmineo}
- {mod-id: healthcare, name: Health Care, version: 1.0.7, authors: samo_lego}
- {mod-id: hologram-api, name: Hologram API, version: 0.1.1+1.17, authors: Patbox}
- {mod-id: holograms, name: Holograms, version: 1.2.0, authors: Me!}
- {mod-id: htm, name: Hey That's Mine, version: 1.1.2, authors: Potatoboy9999}
- {mod-id: hydrogen, name: Hydrogen, version: '0.3', authors: JellySquid}
- {mod-id: illegalstackfixer, name: Illegal Stack Fixer, version: 2.0.0, authors: MrMelon54}
- {mod-id: itemflexer, name: ItemFlexer, version: 1.1.3, authors: TheoreticallyUseful}
- {mod-id: jankson, name: Jankson, version: 3.0.0+j1.2.0, authors: 'Falkreon, The
        Cotton Project'}
- {mod-id: java, name: OpenJDK 64-Bit Server VM, version: '16'}
- {mod-id: keepheadnames, name: Keep Head Names, version: '1.3', authors: Fourmisain}
- {mod-id: krypton, name: Krypton, version: 0.1.3, authors: tuxed}
- {mod-id: lazydfu, name: LazyDFU, version: 0.1.2, authors: tuxed}
- {mod-id: ledger, name: Ledger, version: 1.0.2, authors: Potatoboy9999}
- {mod-id: lithium, name: Lithium, version: 0.7.3, authors: JellySquid}
-   mod-id: loom-generated
    name: Loom Generated
    version: ''
    children:
    - {mod-id: cloud_commandframework_cloud-brigadier, name: cloud-brigadier, version: 1.5.0-SNAPSHOT}
    - {mod-id: cloud_commandframework_cloud-core, name: cloud-core, version: 1.5.0-SNAPSHOT}
    - {mod-id: cloud_commandframework_cloud-minecraft-extras, name: cloud-minecraft-extras,
        version: 1.5.0-SNAPSHOT}
    - {mod-id: cloud_commandframework_cloud-services, name: cloud-services, version: 1.5.0-SNAPSHOT}
    - {mod-id: com_fasterxml_jackson_core_jackson-annotations, name: jackson-annotations,
        version: 2.10.1}
    - {mod-id: com_fasterxml_jackson_core_jackson-core, name: jackson-core, version: 2.10.1}
    - {mod-id: com_fasterxml_jackson_core_jackson-databind, name: jackson-databind,
        version: 2.10.1}
    - {mod-id: com_github_shevek_parallelgzip, name: parallelgzip, version: master-SNAPSHOT}
    - {mod-id: com_google_code_findbugs_jsr305, name: jsr305, version: 3.0.2}
    - {mod-id: com_konghq_unirest-java_standalone, name: unirest-java, version: 3.11.9}
    - {mod-id: com_moandjiezana_toml_toml4j, name: toml4j, version: 0.7.2}
    - {mod-id: com_neovisionaries_nv-websocket-client, name: nv-websocket-client,
        version: '2.14'}
    - {mod-id: com_squareup_okhttp3_okhttp, name: okhttp, version: 3.13.0}
    - {mod-id: com_squareup_okio_okio, name: okio, version: 1.17.2}
    - {mod-id: com_typesafe_config, name: config, version: 1.4.1}
    - {mod-id: com_velocitypowered_velocity-native, name: velocity-native, version: 1.1.0-SNAPSHOT}
    - {mod-id: gs_mclo_java_mclogs-java_, name: mclogs-java, version: 2.0.0}
    - {mod-id: io_leangen_geantyref_geantyref, name: geantyref, version: 1.3.11}
    - {mod-id: net_dv8tion_jda, name: JDA, version: 4.2.1_253}
    - {mod-id: net_kyori_adventure-api, name: adventure-api, version: 4.8.0}
    - {mod-id: net_kyori_adventure-key, name: adventure-key, version: 4.8.0}
    - {mod-id: net_kyori_adventure-platform-api, name: adventure-platform-api, version: 4.0.0-SNAPSHOT}
    - {mod-id: net_kyori_adventure-text-feature-pagination, name: adventure-text-feature-pagination,
        version: 4.0.0-SNAPSHOT}
    - {mod-id: net_kyori_adventure-text-minimessage, name: adventure-text-minimessage,
        version: 4.2.0-SNAPSHOT}
    - {mod-id: net_kyori_adventure-text-serializer-gson, name: adventure-text-serializer-gson,
        version: 4.8.0}
    - {mod-id: net_kyori_adventure-text-serializer-plain, name: adventure-text-serializer-plain,
        version: 4.8.0}
    - {mod-id: net_kyori_examination-api, name: examination-api, version: 1.1.0}
    - {mod-id: net_kyori_examination-string, name: examination-string, version: 1.1.0}
    - {mod-id: net_sf_trove4j_trove4j, name: trove4j, version: 3.0.3}
    - {mod-id: org_apache_commons_commons-collections4, name: commons-collections4,
        version: '4.1'}
    - {mod-id: org_apache_commons_commons-compress, name: commons-compress, version: '1.19'}
    - {mod-id: org_jetbrains_annotations, name: annotations, version: 16.0.1}
    - {mod-id: org_jetbrains_kotlin_kotlin-reflect, name: kotlin-reflect, version: 1.5.20}
    - {mod-id: org_jetbrains_kotlin_kotlin-stdlib, name: kotlin-stdlib, version: 1.5.20}
    - {mod-id: org_jetbrains_kotlin_kotlin-stdlib-jdk7, name: kotlin-stdlib-jdk7,
        version: 1.5.20}
    - {mod-id: org_jetbrains_kotlin_kotlin-stdlib-jdk8, name: kotlin-stdlib-jdk8,
        version: 1.5.20}
    - {mod-id: org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm, name: kotlinx-coroutines-core-jvm,
        version: 1.5.0}
    - {mod-id: org_jetbrains_kotlinx_kotlinx-coroutines-jdk8, name: kotlinx-coroutines-jdk8,
        version: 1.5.0}
    - {mod-id: org_jetbrains_kotlinx_kotlinx-serialization-core-jvm, name: kotlinx-serialization-core-jvm,
        version: 1.2.1}
    - {mod-id: org_jetbrains_kotlinx_kotlinx-serialization-json-jvm, name: kotlinx-serialization-json-jvm,
        version: 1.2.1}
    - {mod-id: org_spongepowered_configurate-core, name: configurate-core, version: 4.1.1}
    - {mod-id: org_spongepowered_configurate-extra-dfu4, name: configurate-extra-dfu4,
        version: 4.1.1}
    - {mod-id: org_spongepowered_configurate-gson, name: configurate-gson, version: 4.1.1}
    - {mod-id: org_spongepowered_configurate-hocon, name: configurate-hocon, version: 4.1.1}
    - {mod-id: org_spongepowered_configurate-yaml, name: configurate-yaml, version: 4.1.1}
    - {mod-id: org_tukaani_xz, name: xz, version: '1.8'}
    - {mod-id: org_yaml_snakeyaml, name: snakeyaml, version: 1.30-SNAPSHOT}
- {mod-id: mclogs, name: Mclogs, version: 1.2.0-for-1.17.x, authors: Julian Vennen}
- {mod-id: microconfig, name: Microconfig, version: 2.0.1}
- {mod-id: minecraft, name: Minecraft, version: '1.17'}
- {mod-id: minimotd-fabric, name: MiniMOTD, version: 2.0.3, authors: jmp}
- {mod-id: mixintrace, name: MixinTrace, version: 1.1.0+1.17, authors: comp500}
- {mod-id: mods-command, name: Mods Command, version: 1.0.3, authors: jmp}
- {mod-id: monsters_in_the_closet, name: Monsters in the Closet, version: 1.0.2+1.17,
    authors: Minenash}
- {mod-id: more_codecs, name: More Codecs, version: 0.1.4, authors: Nucleoid Contributors}
- {mod-id: mostructures, name: Mo' Structures, version: 1.2.0-1.17, authors: frqnny}
- {mod-id: ne-v-seti, name: Ne v seti, version: 0.1.6-1.17, authors: BasiqueEvangelist}
- {mod-id: notenoughcrashes, name: Not Enough Crashes, version: 3.3.1+1.17, authors: 'Fudge,
        Runemoro'}
- {mod-id: omega-config, name: OmegaConfig, version: 1.0.8, authors: 'Draylar, Frqnny'}
- {mod-id: packet_tweaker, name: Packet Tweaker, version: 0.2.0-1.17-pre1, authors: Gegy}
- {mod-id: perfectaccuracy, name: Perfect Accuracy, version: '1.1', authors: Fourmisain}
- {mod-id: pingspam, name: Pingspam, version: 1.2.0-1.17, authors: 'BasiqueEvangelist,
        HotKinkajou'}
- {mod-id: placeholder-api, name: Fabric Placeholder API, version: 1.0.1+1.17, authors: Patbox}
- {mod-id: player_roles, name: Player Roles, version: 1.4.2, authors: Gegy}
- {mod-id: player_roles_api, name: Player Roles API, version: 1.4.2, authors: Gegy}
- {mod-id: playerabilitylib, name: Pal, version: 1.3.0-nightly.1.17-rc1, authors: Pyrofab}
- {mod-id: pvptoggle, name: Pvp Toggle, version: 1.0.4, authors: manyrandomthings}
- {mod-id: quecee, name: Quecee, version: 2.0.1, authors: TheoreticallyUseful / P03W}
- {mod-id: server_translations_api, name: Server Translations API, version: 1.4.5+1.17,
    authors: CatCore}
- {mod-id: servertick, name: Server Tick, version: '1.5', authors: sammko}
- {mod-id: sgui, name: SGui, version: 1.0.0-pre0-1.17-pre1, authors: Patbox}
- {mod-id: sign_editor, name: Better Signs & Frames, version: 0.8.1, authors: CleverCorvid}
- {mod-id: smoothboot, name: Smooth Boot, version: 1.16.5-1.6.0, authors: UltimateBoomer}
- {mod-id: spark, name: spark, version: '${pluginVersion}', authors: Luck}
- {mod-id: starlight, name: Starlight, version: fabric-1.0.0-RC2-3a77ed1, authors: Spottedleaf}
- {mod-id: stitchedsnow, name: Stiched Snow, version: 1.0.3, authors: 'StrikerRocker,
        Slainlight'}
- {mod-id: styledplayerlist, name: Styled Player List, version: 2.1.0, authors: Patbox}
- {mod-id: textile_backup, name: Textile Backup, version: 2.1.0-1.17, authors: Szum123321}
- {mod-id: tweed, name: Tweed API, version: 3.0.0-beta.22, authors: Siphalor}
- {mod-id: villagernames, name: Villager Names, version: 2.0.0, authors: 'Victor (Yumatan),
        OverlordsIII, Fourmisain'}
- {mod-id: voicechat, name: Simple Voice Chat, version: 1.17-1.4.11, authors: Max
        Henkel}
- {mod-id: wandering_collector, name: Wandering Collector, version: 1.0.2+mc1.17,
    authors: Siphalor}
- {mod-id: worldborderfix, name: Worldborderfix, version: 1.2-fabric-1.17, authors: Potatoboy9999}
`

**Comment by martmists-gh** [comment]
> {mod-id: fabric-permissions-api-v0, name: fabric-permissions-api, version: 0.1-SNAPSHOT,
authors: Luck}
This is an incompatible permission API, we use one made by Patbox.
