### ISSUE TITLE
Fix SQLite Compatibility issues with other mods using SQLite

### ISSUE THREAD

**Issue by AchalS-iglu** [Gunpowder-MC/Gunpowder#120]
**Information**
- Minecraft Version: 1.17.1
- Fabric API Version: 37
- OS: Server on pterodactyl / ubuntu
- Other installed mods: Ledger

**Describe the issue**
With mod Ledger ( https://www.curseforge.com/minecraft/mc-mods/ledger ) the other mod doesn't work. Apparently according to ledger dev they have fixed the issue on their side. https://github.com/QuiltServerTools/Ledger/issues/13

**Crash/Error logs**
https://pastebin.com/z8dGwxvi

Kindly give a read to the issue I linked above. Thanks!
Sorry if I am wrong.

**Comment by red2blue** [comment]
same shit happens if you try mysql

**Comment by martmists-gh** [comment]
I don't see how ledger would still be incompatible, it should work fine from what I can see. Alternatively they could use gunpowder's database when present, but it seems they preferred their current method.

**Comment by red2blue** [comment]
Maybe it was compat in ledger < 2 and with their update it had new
problems? I'll report to ledger team.

**Comment by red2blue** [comment]
Reached out to them, they mentioned that it isn’t compat due to “Gunpowder is incompatible with Ledger because both mods use Exposed and Gunpowder does not shade Exposed.”

**Comment by red2blue** [comment]
So... are you going to make it compatible?

**Comment by martmists-gh** [comment]
Gunpowder already offers tools for developers to use exposed in a non-breaking way. If other developers refuse to work with this that's on them. If I were to relocated exposed, it would make development of gunpowder modules incredibly complicated for other developers, and that's why we've chosen not to do so in the past.
