### ISSUE TITLE
Conflict With Carpet 1.4.51 Also Crash after Remove carpet 

### ISSUE THREAD

**Issue by SuryaRajgor** [Gunpowder-MC/Gunpowder#123]
**Information**
- Minecraft Version: 1.17.1
- Fabric API Version: 0.42.1 1.17
- OS: Linux (amd64) version 4.19.0-14-amd64
- Other installed mods: many Conflict With Carpet 1.4.51 but after removed

**Describe the issue**
A first server crash and Give Error Conflict With Carpet 1.4.51 after I removed and Start Server
then when I tried to join the server will be crashed and also without joining its crash after some time

**Crash/Error logs**
Log = https://pastebin.com/27hGDSe1
Crash Report = https://pastebin.com/jNg893kQ
Log With Carpet = https://pastebin.com/053jXS88

**To Reproduce**
Steps to reproduce the behaviour:
1. server Runs fine
2. i want to use currency and discord WL
3. so i put mod gunpowder base, currency, Discord Wl and Also Grand Economy
4. after start-server but its show gunpowder conflict with carpet
5. so i remove the carpet mod and try to start and when server start I try to join but immediately server crash

**Expected behaviour**
its work with server . ;)

**Additional context**
new aaded mod files 
gunpowder-base-1.0.6.3+1.17.1.jar
gunpowder-currency-1.0.7+gunpowder.1.0.6.3.mc.1.17.1.jar
gunpowder-discord-whitelist-1.0.2+gunpowder.1.0.6.3.mc.1.17.1
Grand-Economy-5.1.0+1.17.1.jar
Fireplace-Lib-6.2.0+1.17.1.jar

**Comment by martmists-gh** [comment]
java.lang.NoClassDefFoundError: eu/pb4/permissions/api/v0/Permissions

It seems the permission API we need doesn't exist, despite the fact that it *should* be bundled in the 1.17.1 release. Try again after adding this mod: https://github.com/Patbox/ServerPermissionsAPI/releases/download/0.1.0-alpha1/permissions-api-0.1.0-alpha1.jar

**Comment by SuryaRajgor** [comment]
its Work And What About Conflict With Carpet Mode should i try to run with it??

**Comment by martmists-gh** [comment]
I don't see any issues with carpet, you just didn't configure the mod yet in that crash log.

**Comment by SuryaRajgor** [comment]
Log With Carpet = https://pastebin.com/053jXS88 before Fix
 - Mod 'Gunpowder' (gunpowder-base) conflicts with any version of mod 'Carpet Mod' (carpet), which is present with the following versions: 1.4.51!
	 - While this won't prevent you from starting the game, the developer(s) of mod 'Gunpowder' (gunpowder-base) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.
	 - Mod 'Carpet Mod' (carpet) 1.4.51 is being loaded from /home/zap442952/g352297/fabric/mods/fabric-carpet-1.17.1-1.4.51+v211028.jar 

[latest.log](https://github.com/Gunpowder-MC/Gunpowder/files/7585102/latest.log)

**Comment by martmists-gh** [comment]
As you can see that's just a warning. 
In your log: `javax.security.auth.login.LoginException: The provided token is invalid!`
It seems you didn't configure the discord whitelist mod properly.

**Comment by SuryaRajgor** [comment]
this is old Log first run
i put Latest.log in the attachment 
hear it is https://pastebin.com/053jXS88

**Comment by SuryaRajgor** [comment]
Mod 'Gunpowder' (gunpowder-base) conflicts with any version of mod 'Carpet Mod' (carpet), which is present with the following versions: 1.4.51!
	 - While this won't prevent you from starting the game, the developer(s) of mod 'Gunpowder' (gunpowder-base) have found that this combination may cause issues. You should remove one of the mods or check for updates that resolve the issue.

**Comment by martmists-gh** [comment]
That's just a warning, not an error. If you could read, you'd see that it says we have found that it often causes issues.
