### ISSUE TITLE
Server Crash on startup

### ISSUE THREAD

**Issue by DriveBy123** [Gunpowder-MC/Gunpowder#124]
**Information**
- Minecraft Version: 1.17.1 server
- Fabric API Version: 0.43.1
- OS: Windows
- Other installed mods: fabric api, clumps, attribute fix, kotlin lib, FabricHomes, FabricTPA, Fabric Warps, flytre lib, gunpowder base

**Describe the issue**
Gunpowder base causes my server to crash whenever a player joins the server. I tested all of my mods one by one to figure out which mod was conflicting and found out that it seems to be crashing whenever I am using the FabricTPA mod. So the server starts up fine and is running but when someone joins (me for example) it immediately crashes the server and makes a bunch of error codes and tries to restart the server. 

**Crash/Error logs**
https://pastebin.com/3aRjeSjN

**To Reproduce**
Download gunpowder base for 1.17.1 and Fabric TPA 1.17.1 and place into mods folder.
Start the server, once spawn was setup join the server
The server Crashes.

Oh and ledger also crashes with gunpowder but that was an issuse already addressed.

**Comment by martmists-gh** [comment]
https://github.com/Patbox/ServerPermissionsAPI/releases

Download the permissions API from here, it seems a different mod might override it.
