### ISSUE TITLE
Permissions Stalls server

### ISSUE THREAD

**Issue by LemonadeSerg** [Gunpowder-MC/Gunpowder#127]
Run server
Attemt to list players permissions works fine
Attempt to add new permission doesn't work and causes crash.

Full log https://pastebin.com/qVUgKrKw

I believe this could be the issue

06.01 20:15:44 [Server] Gunpowder Database Thread/ERROR Uncaught exception in thread "Gunpowder Database Thread"
06.01 20:15:45 [Server] INFO java.lang.StackOverflowError: null
06.01 20:15:45 [Server] INFO at kotlin.text.StringsKt__StringsKt.indexOf(Strings.kt:1105) ~[org_jetbrains_kotlin_kotlin-stdlib-1.6.10-cf953ebebc036e3.jar:?]
06.01 20:15:45 [Server] INFO at kotlin.text.StringsKt__StringsKt.split$StringsKt__StringsKt(Strings.kt:1349) ~[org_jetbrains_kotlin_kotlin-stdlib-1.6.10-cf953ebebc036e3.jar:?]
06.01 20:15:45 [Server] INFO at kotlin.text.StringsKt__StringsKt.split(Strings.kt:1331) ~[org_jetbrains_kotlin_kotlin-stdlib-1.6.10-cf953ebebc036e3.jar:?]
06.01 20:15:45 [Server] INFO at kotlin.text.StringsKt__StringsKt.split$default(Strings.kt:1329) ~[org_jetbrains_kotlin_kotlin-stdlib-1.6.10-cf953ebebc036e3.jar:?]
06.01 20:15:45 [Server] INFO at io.github.gunpowder.entities.PermissionTree.getOrCreate(PermissionTree.kt:46) ~[gunpowder-permissions-1.0.1+gunpowder.1.0.6.3.mc.1.17.1.jar:?]

**Comment by martmists-gh** [comment]
This error does not appear in the full log provided. In fact, I don't see any error in the log relating to gunpowder at all.
