### ISSUE TITLE
Port WorldGuard to Fabric

### ISSUE THREAD

**Issue by TechPro424** [Gunpowder-MC/Gunpowder#132]
**Describe what you'd like**
I read in #29 that with the Claims API in place you are starting looking at porting claims mods such as Towny. Would it be possible to port WorldGuard using the same API or would there be a need for another one?

WorldGuard: https://dev.bukkit.org/projects/worldguard/

**Comment by PortableGames** [comment]
Residence 🤘

**Comment by TechPro424** [comment]
> Residence 🤘

wdym
