### ISSUE TITLE
McMMO Port

### ISSUE THREAD

**Issue by martmists-gh** [Gunpowder-MC/Gunpowder#34]
**Describe what you'd like**
An McMMO port for Fabric has been requested several times in Fabricord.

**Comment by CamperSamu** [comment]
there is already an mcmmo-like mod called [RPGStats](https://www.curseforge.com/minecraft/mc-mods/rpgstats), it's not the same tho...
It can be a starting point.

**Comment by redcreeper14385** [comment]
Would this be optional?

**Comment by martmists** [comment]
redcreeper14385: It will be in its separate module, so yes

**Comment by martmists-gh** [comment]
MCMMO is considering official fabric support in the future:
https://github.com/mcMMO-Dev/mcMMO/issues/4510
