### ISSUE TITLE
Chest Locking

### ISSUE THREAD

**Issue by creepystalker2** [Gunpowder-MC/Gunpowder#43]
**Describe what you'd like**
I would like some way to lock chests to make them accessible to only the player who locked them.

**Additional context**
Could be locked with either a sign with specific text on it or a command, whichever would be easier to implement. Ideally somebody with permissions would be able to bypass the lock. Idea behind this comes from my desire to have a fabric alternative to spigot plugins like this one: https://www.spigotmc.org/resources/lockettepro-uuid-support-abandoned.20427/ (LockettePro).

**Comment by martmists-gh** [comment]
There's a fair amount of mods for this I believe.
