### ISSUE TITLE
Crash with currency module

### ISSUE THREAD

**Issue by Ninjajax66** [Gunpowder-MC/Gunpowder#79]
**Information**
- Minecraft Version: 1.16.2
- Fabric API Version: 0.17.2+build.396-1.16
- OS: Windows
- Other installed mods: 
![Untitled drawing (2)](https://user-images.githubusercontent.com/67060979/90327009-73719e80-df5d-11ea-9afd-a21d161a169b.png)

**Describe the issue**
When currency module is installed it crashes

**Crash/Error logs**
[Crash](https://hastebin.com/ijuxejesag.js)

**To Reproduce**
1. Download mods
2. launch game
3. See crash

**Expected behavior**
I expect to load the game without any crash screen.

**Additional context**
none

**Comment by magneticflux-** [comment]
This might be the problem: https://github.com/Gunpowder-MC/GunpowderMarket/blob/ea23e49ff3371a933082ffb77784bbd63e11eb74/build.gradle#L10
@i509VCB

**Comment by martmists** [comment]
We've tried changing kotlin version to various versions, it still worked for the users it worked for but not for the users it didn't.

**Comment by Ninjajax66** [comment]
also does the same thing with only the utilities module installed

**Comment by martmists** [comment]
Unable to reliably reproduce, user in our support channel claims the CF jars work fine whereas they didn't before.
