### ISSUE TITLE
Crash on server load

### ISSUE THREAD

**Issue by systemm0** [Gunpowder-MC/Gunpowder#80]
**Information**
- Minecraft Version: 1.16.2
- Fabric API Version: fabric-api-0.18.0+build.397-1.16
- OS: Ubuntu
- Other installed mods: 
appliedenergistics2-fabric-8.1.0-alpha.1.
astromine-1.6.1+fabric-1.16.2
dynmap-fabric-0.2.12+1.16.2
fabric-chunkpregen-0.2.2
facility-mc116-0.11.184
gunpowder base 0.2.9
all the other gunpowder modules
 - currency
 - market
 - teleport
 - utilities

** what happened **
server boot up.. no go brrrrrr

**logs**
https://controlc.com/8250e624

**To Reproduce**
run a server

**Expected behavior**
server boot up... go brrrrrr

**Comment by martmists** [comment]
Install PlayerAbilityLib
