### ISSUE TITLE
Resource Packs Will Not Automatically Be Downloaded By Vanilla Clients

### ISSUE THREAD

**Issue by IAmSneak** [Gunpowder-MC/Gunpowder#83]
**Information**
- Minecraft Version: 1.16.2
- Fabric API Version: 0.19.0 build 398 1.16
- OS: Windows
[- Other Installed Mods](https://docs.google.com/document/d/15mDhf2LQ9RBxgWur2kbsy3UPOMciUV9kqP0qbASqYXo/edit?usp=sharing)

When trying to join a server with a resource pack that is automatically installed, the resource pack will not be installed. When trying to join with a fabric client (even with no mods) it will work perfectly. After removing gunpowder, sleep vote, currency, and marketplace, the client will be prompted to install the resource pack.

1. Create a server with an automatically downloading resource pack in server.properties
2. Join a server with a vanilla client
3. Resource pack won't attempt to load

Expected Behavior:
Resource pack automatically downloaded or client asked to download it.

**Comment by MaryWeeb** [comment]
Unable to reproduce with just gunpowder and modules. Please figure out the minimum required mods to reproduce this issue.

**Comment by martmists-gh** [comment]
Does this still happen in latest versions?

**Comment by IAmSneak** [comment]
Didn't know this one was still open. If I remember correctly, this was caused by me not joining with server resource packs enabled / accidentally declining.
