### ISSUE TITLE
Gunpowder Crashes Without PlayerAbilityLib

### ISSUE THREAD

**Issue by amnotbananaama** [Gunpowder-MC/Gunpowder#87]
**Information**
- Minecraft Version: 1.16.2
- Fabric API Version: 0.20.1+build.401-1.16
- OS: Windows
- Other installed mods: Not Applicable

**Describe the issue**
If [PlayerAbilityLib](https://github.com/Ladysnake/PlayerAbilityLib) isn't present in the user's mods, Gunpowder crashes with  `java.lang.ClassNotFoundException`.

**Crash/Error logs**
https://pastebin.com/raw/vtr23hZy

**To Reproduce**
1. Have Gunpowder base and fabric api, don't have PlayerAbilityLib.
2. Start the server
4. Server crashes

**Expected behavior**
PlayerAbilityLib should be bundled or jar-in-jared with Gunpowder, as it is a required library dependency. From PlayerAbilityLib's CF page: 
> Players should not have to download this library themselves, as it is intended to be embedded in distributed jar files.

**Additional context**
N/A

**Comment by amnotbananaama** [comment]
Just saw #80 , if you decide not to embed it for some reason, it should be listed somewhere (on CurseForge, in the README) that users need to download this, rather than wasting time locating a missing dependency *after* the crash happens

**Comment by MaryWeeb** [comment]
Fixed in dev, it will crash at boot and open a window saying it's missing PAL.
