### ISSUE TITLE
Cannot find a native class on macOS

### ISSUE THREAD

**Issue by YTG1234** [Gunpowder-MC/Gunpowder#89]
**Information**
- Minecraft Version: 1.16.4
- Fabric API Version: 0.29.3+1.16
- OS: macOS
- Other installed mods: Can be found in log.

**Describe the issue**
Game crashes on startup with a `ClassNotFoundException`.

**Crash/Error logs**
If the game crashes or console errors are present, please attach the log here using a text paste service (such as gist or hastebin): https://paste.ee/p/tAQnQ (Ignore the NEC part, that's just NEC being NEC) Process was killed because I don't want to wait for NEC to show the error.

**To Reproduce**
1. Install Gunpowder
1. Open Minecraft

**Expected behavior**
Minecraft loads as usual.

**Additional information**
I'm using Java 15.0.1, OpenJ9.

**Comment by YTG1234** [comment]
HotSpot works.

**Comment by MaryWeeb** [comment]
This seems to be an issue with SQLite-JDBC
