### ISSUE TITLE
Internationalization support

### ISSUE THREAD

**Issue by yhr0x43** [Gunpowder-MC/Gunpowder#92]
Allow configuration of messages send to client for translation.

Currently all messages are hard-coded. If the server admin wants to make the server friendly to non-English players, the only way to do so is to read through the code, change every line, and recompile. This is not optimal.

I would personally loved to see the approach utilizing server-translation-api like what NucleoidMC has done [here](https://github.com/NucleoidMC/plasmid/blob/e550c9a2a60a440c041602a5c62db8825d135623/build.gradle#L44), which allows detection of client language setting and send correct text.
If adding more library is not desired. Simply have a lang file that allows the server admin to customize will be a great improvement.

**Comment by martmists-gh** [comment]
We have a TranslatableText class, and we're looking to add configs for these when we've got time to develop again.

**Comment by yhr0x43** [comment]
I see, thank you for clarify. That sounds amazing.

I read a bit into the translation classes. So if not mistaken, the translation support with client setting detection is complete.
I would also like to help implement this system in all official modules

**Comment by martmists-gh** [comment]
PRs are welcome. You can refer to this issue in those PRs as a "master issue" if you'd like.

**Comment by yhr0x43** [comment]
As the reason why this issue exist is my ignorance of TranslatableText class. I think it is proper to just close it.
