### ISSUE TITLE
Server Crashing with Origin

### ISSUE THREAD

**Issue by edred59** [Gunpowder-MC/Gunpowder#96]
**Information**
- Minecraft Version: 1.16.5
- Fabric API Version: 0.30.3+1.16
- OS: Windows

Other installed mods: 
- All of Fabric 3 (ver 2.6.10) Modlist
- Origins, Origin: Classes, Haema, extraorigins, moborigins, Pehkui
- Gunpowder, Gunpowder tp, sleepvote and utilities.

**Describe the issue**
Server crashes on startup

**Crash/Error logs**
https://pastebin.com/a37yAdSF

**To Reproduce**
Opening the server

**Expected behavior**
Server starts

**Additional context**
Using the All of Fabric 3 (2.6.10) modpack with origin mods on a self host server.

**Comment by martmists-gh** [comment]
Needs fixing by Haema's devs; They've been notified, but I'll leave the issue open for now.
